# Generated by Django 5.2.5 on 2025-09-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_detected_destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
